from enum import Enum, auto


class LogCode(Enum):
    WIN = auto()
    LOSE = auto()
    ACTION_START = auto()
    ACTION_BLOCKED = auto()
    CONSUME_PP = auto()
    MOVE_USED = auto()
    MOVE_IMMUNE = auto()
    PROTECT_SUCCESS = auto()
    PROTECT_FAILED = auto()
    HP_CHANGED = auto()
    MODIFY_STAT = auto()
    SWITCH_IN = auto()
    SWITCH_OUT = auto()
    LOSE_ITEM = auto()
    CURE_AILMENT = auto()
    APPLY_AILMENT = auto()
    ABILITY_TRIGGERED = auto()
    ITEM_TRIGGERED = auto()
    VOLATILE_APPLIED = auto()
    VOLATILE_REMOVED = auto()
    VOLATILE_STATUS = auto()
    HEAL_BLOCKED = auto()
    HIT_SUBSTITUTE = auto()
    TEXT_LOG = auto()
